apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: githubaction-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/prithvi081099/github-ArgoCD.git
    targetRevision: dev
    path: gitOpsArgoCD
    helm:
      containerName: dev
      containerVersion: v1
  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true 
